[theme]
primaryColor="#009DDC"             # Light blue
backgroundColor="#FFFFFF"          # White background
secondaryBackgroundColor="#E8E2D6" # Sand beige panels
textColor="#002B49"                # Dark blue text
font="sans serif"
